name: Github action with quicktype test
run-name: ${{ github.actor}} is testing out Github actions with quicktype
on: [pull_request]
jobs:
  check-a-quicktype-version-and-run-a-test:
      runs-on: ubuntu-latest
      steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
                ref: ${{github.event.push.sha}}
            - run: npm install -g quicktype
            - run: |
                echo '{ "name": "David" }' | quicktype -l csharp

