name: Learn-github-action
run-name: ${{github.actor}} is running
on: [push]
jobs:
    check-bats-version:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
            - run: npm i bats
            - run: bats --version